export interface SubclassLevelUnlock {
  level: number;
  features: string[];
}

export type ClassDifficulty = 'beginner' | 'intermediate' | 'expert';
export type ClassRoleType = 'attacker' | 'tank' | 'support' | 'controller';

export interface ClassDefinition {
  role: string;
  playstyleBlurb: string;
  keyStats: string[];
  hitDie: number;
  highlightFeature: string;
  subclassTerm: string;
  subclassLevel: number;
  difficulty: ClassDifficulty;
  roleType: ClassRoleType;
  difficultyNote: string;
  baseLevelUnlocks: SubclassLevelUnlock[];
}

export const CLASS_DEFINITIONS: Record<string, ClassDefinition> = {
  Fighter: {
    role: 'Martial striker',
    playstyleBlurb: 'A master of weapons and armor who excels at sustained combat.',
    keyStats: ['STR', 'CON'],
    hitDie: 10,
    highlightFeature: 'Action Surge',
    subclassTerm: 'Martial Archetype',
    subclassLevel: 3,
    difficulty: 'beginner',
    roleType: 'attacker',
    difficultyNote: 'No spells to track — attack, use Second Wind to heal, Action Surge for a burst round.',
    baseLevelUnlocks: [
      { level: 1, features: ['Fighting Style — choose a combat specialty (archery, defense, dueling, etc.)', 'Second Wind — bonus action to regain 1d10 + Fighter level HP once per short rest'] },
      { level: 2, features: ['Action Surge — take a full extra action once per short rest'] },
      { level: 5, features: ['Extra Attack — attack twice when you take the Attack action'] },
      { level: 11, features: ['Extra Attack (2) — attack three times per Attack action'] },
      { level: 20, features: ['Extra Attack (3) — attack four times per Attack action'] },
    ],
  },
  Rogue: {
    role: 'Skilled striker',
    playstyleBlurb: 'A cunning infiltrator who strikes from the shadows for devastating sneak attacks.',
    keyStats: ['DEX'],
    hitDie: 8,
    highlightFeature: 'Sneak Attack',
    subclassTerm: 'Roguish Archetype',
    subclassLevel: 3,
    difficulty: 'intermediate',
    roleType: 'attacker',
    difficultyNote: 'Position for Sneak Attack and decide when to use Cunning Action — no spells, but tactics matter.',
    baseLevelUnlocks: [
      { level: 1, features: ['Sneak Attack (1d6) — bonus damage when you have advantage or an ally is adjacent to the target', 'Expertise — double Proficiency on 2 chosen skills'] },
      { level: 2, features: ['Cunning Action — Dash, Disengage, or Hide as a bonus action each turn'] },
      { level: 5, features: ['Uncanny Dodge — halve the damage from one attack per round as a reaction'] },
      { level: 7, features: ['Evasion — take no damage on a successful DEX save (half on failure)'] },
      { level: 11, features: ['Reliable Talent — any skill roll below 10 counts as 10 (for proficient skills)'] },
      { level: 18, features: ['Elusive — attacks against you can never have advantage'] },
    ],
  },
  Barbarian: {
    role: 'Frontline tank',
    playstyleBlurb: 'A fierce warrior who channels primal rage for explosive combat power.',
    keyStats: ['STR', 'CON'],
    hitDie: 12,
    highlightFeature: 'Rage',
    subclassTerm: 'Primal Path',
    subclassLevel: 3,
    difficulty: 'beginner',
    roleType: 'tank',
    difficultyNote: 'Rage gives a big damage boost; d12 HP absorbs your mistakes.',
    baseLevelUnlocks: [
      { level: 1, features: ['Rage — bonus action to resist damage and deal bonus damage for 1 minute (STR attacks only)', 'Unarmored Defense — AC = 10 + DEX mod + CON mod without armor'] },
      { level: 2, features: ['Reckless Attack — advantage on your attacks (enemies also have advantage on you)', 'Danger Sense — advantage on DEX saves vs visible threats'] },
      { level: 5, features: ['Extra Attack — attack twice when you take the Attack action', 'Fast Movement — +10ft speed while not in heavy armor'] },
      { level: 7, features: ['Feral Instinct — advantage on Initiative; act even while surprised if you Rage immediately'] },
      { level: 11, features: ['Relentless Rage — DC 10 CON save to stay at 1 HP when you would drop to 0 while raging'] },
      { level: 20, features: ['Primal Champion — +4 STR and +4 CON permanently'] },
    ],
  },
  Ranger: {
    role: 'Skirmisher',
    playstyleBlurb: 'A hunter who tracks and outmaneuvers enemies in any terrain.',
    keyStats: ['DEX', 'WIS'],
    hitDie: 10,
    highlightFeature: 'Favored Enemy',
    subclassTerm: 'Ranger Archetype',
    subclassLevel: 3,
    difficulty: 'intermediate',
    roleType: 'attacker',
    difficultyNote: 'Mix martial attacks with a short prepared spell list and terrain bonuses.',
    baseLevelUnlocks: [
      { level: 1, features: ['Favored Enemy — advantage on tracking, recall, and survival checks vs chosen enemy type', 'Natural Explorer — ignore difficult terrain and have other travel benefits in chosen terrain'] },
      { level: 2, features: ['Fighting Style — choose a combat specialty', 'Spellcasting — cast ranger spells using WIS'] },
      { level: 5, features: ['Extra Attack — attack twice when you take the Attack action'] },
      { level: 8, features: ["Land's Stride — move through non-magical difficult terrain at no extra cost"] },
      { level: 14, features: ['Vanish — Hide as a bonus action; cannot be tracked by non-magical means'] },
      { level: 20, features: ["Foe Slayer — add WIS modifier to one attack or damage roll vs Favored Enemy per turn"] },
    ],
  },
  Paladin: {
    role: 'Melee support',
    playstyleBlurb: 'A holy warrior who smites foes and heals allies with divine power.',
    keyStats: ['STR', 'CHA'],
    hitDie: 10,
    highlightFeature: 'Divine Smite',
    subclassTerm: 'Sacred Oath',
    subclassLevel: 3,
    difficulty: 'intermediate',
    roleType: 'support',
    difficultyNote: 'Decide each hit whether to spend spell slots on Divine Smite damage or save them for healing.',
    baseLevelUnlocks: [
      { level: 1, features: ['Divine Sense — detect celestials, fiends, and undead within 60ft', 'Lay on Hands — heal from a pool of HP equal to 5× your Paladin level'] },
      { level: 2, features: ['Divine Smite — expend a spell slot on a hit for +2d8 radiant (scales up with slot level)', 'Spellcasting — cast paladin spells using CHA'] },
      { level: 5, features: ['Extra Attack — attack twice when you take the Attack action'] },
      { level: 6, features: ['Aura of Protection — you and allies within 10ft add your CHA modifier to all saving throws'] },
      { level: 10, features: ['Aura of Courage — you and allies within 10ft are immune to fright'] },
      { level: 11, features: ['Improved Divine Smite — all your melee hits deal +1d8 radiant, no spell slot needed'] },
    ],
  },
  Monk: {
    role: 'Mobile striker',
    playstyleBlurb: 'A martial artist who channels ki for blinding speed and unarmed lethality.',
    keyStats: ['DEX', 'WIS'],
    hitDie: 8,
    highlightFeature: 'Ki',
    subclassTerm: 'Monastic Tradition',
    subclassLevel: 3,
    difficulty: 'intermediate',
    roleType: 'attacker',
    difficultyNote: 'Ki refreshes on short rest, but you need to decide which options are worth spending it on.',
    baseLevelUnlocks: [
      { level: 1, features: ['Martial Arts — use DEX for unarmed strikes and monk weapons; bonus unarmed attack after attacking', 'Unarmored Defense — AC = 10 + DEX mod + WIS mod without armor'] },
      { level: 2, features: ['Ki (= Monk level) — spend for Flurry of Blows (2 extra hits), Patient Defense (Dodge), or Step of the Wind (Disengage + jump)', 'Unarmored Movement — +10ft speed (increases at higher levels)'] },
      { level: 3, features: ['Deflect Missiles — reduce ranged weapon damage as a reaction; spend 1 Ki to throw it back'] },
      { level: 5, features: ['Extra Attack — attack twice when you take the Attack action', 'Stunning Strike — spend 1 Ki after a hit; target CON save or stunned until your next turn'] },
      { level: 6, features: ['Ki-Empowered Strikes — your unarmed attacks count as magical'] },
      { level: 14, features: ['Diamond Soul — proficiency in all saving throws; spend 1 Ki to reroll a failed save'] },
    ],
  },
  Cleric: {
    role: 'Divine support',
    playstyleBlurb: 'A divine conduit who heals allies and channels holy power in combat.',
    keyStats: ['WIS'],
    hitDie: 8,
    highlightFeature: 'Channel Divinity',
    subclassTerm: 'Divine Domain',
    subclassLevel: 1,
    difficulty: 'expert',
    roleType: 'support',
    difficultyNote: 'Juggle prepared spells, Channel Divinity, and concentration while keeping allies alive.',
    baseLevelUnlocks: [
      { level: 1, features: ['Spellcasting — prepare and cast Cleric spells using WIS; Domain chosen now adds bonus spells always prepared', 'Channel Divinity — use powerful divine effects (charges recharge on short rest)'] },
      { level: 2, features: ['Turn Undead — Channel Divinity: force undead within 30ft to flee (WIS save)'] },
      { level: 5, features: ['Destroy Undead — weaker undead are instantly destroyed rather than turned'] },
      { level: 6, features: ['Channel Divinity (2/rest) — recharges twice per short rest instead of once'] },
      { level: 10, features: ['Divine Intervention — call on your deity; 10% chance they send miraculous aid (guaranteed at L20)'] },
      { level: 20, features: ['Divine Intervention (guaranteed) — your deity always answers when called'] },
    ],
  },
  Druid: {
    role: 'Versatile caster',
    playstyleBlurb: 'A nature priest who shapeshifts into beasts and calls on elemental forces.',
    keyStats: ['WIS'],
    hitDie: 8,
    highlightFeature: 'Wild Shape',
    subclassTerm: 'Druid Circle',
    subclassLevel: 2,
    difficulty: 'expert',
    roleType: 'controller',
    difficultyNote: 'Wild Shape and a full prepared spell list are two separate resource pools to manage.',
    baseLevelUnlocks: [
      { level: 1, features: ['Spellcasting — prepare and cast Druid spells using WIS; prepare from the full Druid list each day'] },
      { level: 2, features: ['Wild Shape (CR ¼) — transform into a beast as an action (2 uses/short rest)', 'Druid Circle — choose your circle at L2 for powerful bonuses'] },
      { level: 4, features: ['Wild Shape (CR ½) — transform into stronger beasts like wolves and crocodiles'] },
      { level: 8, features: ['Wild Shape (CR 1) — transform into dangerous beasts like tigers or giant eagles'] },
      { level: 18, features: ['Beast Spells — cast Druid spells while in Wild Shape form'] },
      { level: 20, features: ['Archdruid — unlimited Wild Shape uses; ignore verbal and somatic spell components'] },
    ],
  },
  Wizard: {
    role: 'Arcane controller',
    playstyleBlurb: 'A scholar of magic who bends reality with devastating spells.',
    keyStats: ['INT'],
    hitDie: 6,
    highlightFeature: 'Arcane Recovery',
    subclassTerm: 'Arcane Tradition',
    subclassLevel: 2,
    difficulty: 'expert',
    roleType: 'controller',
    difficultyNote: 'Largest spell list in the game — preparation and concentration decisions define every session.',
    baseLevelUnlocks: [
      { level: 1, features: ['Spellcasting — prepare spells from your spellbook using INT; copy any Wizard spell you find into it', 'Arcane Recovery — regain spell slots totaling up to ½ your Wizard level on a short rest (1/long rest)'] },
      { level: 2, features: ['Arcane Tradition — specialize in a school of magic that grants powerful passive bonuses'] },
      { level: 6, features: ['Tradition feature — a major upgrade to your school specialization'] },
      { level: 10, features: ['Tradition feature'] },
      { level: 18, features: ['Spell Mastery — cast one L1 and one L2 spell from your book at will, without using a slot'] },
      { level: 20, features: ['Signature Spells — two L3 spells always prepared; cast each once per day without a slot'] },
    ],
  },
  Bard: {
    role: 'Jack of all trades',
    playstyleBlurb: 'A performer whose magic inspires allies and distracts enemies.',
    keyStats: ['CHA'],
    hitDie: 8,
    highlightFeature: 'Bardic Inspiration',
    subclassTerm: 'Bard College',
    subclassLevel: 3,
    difficulty: 'intermediate',
    roleType: 'support',
    difficultyNote: 'Balance when to hand out Inspiration dice vs saving them for clutch ability checks.',
    baseLevelUnlocks: [
      { level: 1, features: ['Spellcasting — cast Bard spells (known list, no preparation) using CHA', 'Bardic Inspiration (d6) — grant an ally a d6 to add to one roll; recharges on long rest (CHA mod uses)'] },
      { level: 2, features: ['Jack of All Trades — add half Proficiency to any skill you are not proficient in'] },
      { level: 3, features: ['Expertise — double Proficiency on 2 chosen skills', 'Bard College — choose a College that shapes your support or combat style'] },
      { level: 5, features: ['Bardic Inspiration (d8) — stronger dice', 'Font of Inspiration — Bardic Inspiration now recharges on short rests'] },
      { level: 10, features: ['Magical Secrets — learn 2 spells from any class spell list'] },
      { level: 20, features: ['Superior Inspiration — if you have no Inspiration dice on initiative, you immediately regain 1'] },
    ],
  },
  Sorcerer: {
    role: 'Innate blaster',
    playstyleBlurb: 'A natural spellcaster who bends magic with Metamagic techniques.',
    keyStats: ['CHA'],
    hitDie: 6,
    highlightFeature: 'Metamagic',
    subclassTerm: 'Sorcerous Origin',
    subclassLevel: 1,
    difficulty: 'expert',
    roleType: 'attacker',
    difficultyNote: 'Metamagic choices require knowing which spell combos are worth burning Sorcery Points on.',
    baseLevelUnlocks: [
      { level: 1, features: ['Spellcasting — cast Sorcerer spells (known list) using CHA; Origin chosen now grants innate powers'] },
      { level: 2, features: ['Font of Magic — Sorcery Points (= Sorcerer level) convert to/from spell slots', 'Flexible Casting — spend 1–5 points to create a spell slot, or convert a slot into points'] },
      { level: 3, features: ['Metamagic (2 options) — modify spells: Twin (hit two targets), Quicken (cast as bonus action), Subtle (no verbal/somatic), Empower (reroll damage dice), and more'] },
      { level: 6, features: ['Origin feature — a major boost from your Sorcerous Origin'] },
      { level: 10, features: ['Metamagic (3rd option) — learn one additional Metamagic'] },
      { level: 20, features: ['Sorcerous Restoration — regain 4 Sorcery Points on a short rest'] },
    ],
  },
  Warlock: {
    role: 'Eldritch striker',
    playstyleBlurb: 'A pact-bound caster with limited but rechargeable spell slots.',
    keyStats: ['CHA'],
    hitDie: 8,
    highlightFeature: 'Eldritch Blast',
    subclassTerm: 'Otherworldly Patron',
    subclassLevel: 1,
    difficulty: 'intermediate',
    roleType: 'attacker',
    difficultyNote: 'Only 2 spell slots, but they recharge on short rests — Eldritch Blast fills every gap.',
    baseLevelUnlocks: [
      { level: 1, features: ['Pact Magic — CHA-based spell slots that recharge on a short rest (not long rest)', 'Patron features — your Patron grants bonus spells and unique features chosen now'] },
      { level: 2, features: ['Eldritch Invocations (2) — permanent passive upgrades (e.g., see 120ft in darkness, unlimited Disguise Self, push targets with Eldritch Blast)'] },
      { level: 3, features: ['Pact Boon — choose a familiar (Chain), a conjured weapon (Blade), or a book of arcane secrets (Tome)'] },
      { level: 5, features: ['Spell slots become L3 — your few slots hit harder as you level', 'Eldritch Blast adds a third beam'] },
      { level: 11, features: ['Mystic Arcanum (L6 spell) — one high-level spell per long rest, outside your Pact slots'] },
      { level: 20, features: ['Eldritch Master — spend 1 minute communing with your patron to regain all Pact spell slots'] },
    ],
  },
};

export const SUBCLASS_LEVEL_UNLOCKS: Record<string, Record<string, SubclassLevelUnlock[]>> = {
  Fighter: {
    champion: [
      { level: 3, features: ['Improved Critical — crit on 19–20'] },
      { level: 7, features: ['Remarkable Athlete — add ½ Prof to unmodified STR/DEX/CON checks; +5ft running jump'] },
      { level: 10, features: ['Additional Fighting Style'] },
      { level: 15, features: ['Superior Critical — crit on 18–20'] },
    ],
    battle_master: [
      { level: 3, features: ['Combat Superiority — 4 superiority dice (d8), 4 maneuvers of your choice', 'Student of War — proficiency in one artisan tool'] },
      { level: 7, features: ["Know Your Enemy — learn a foe's ability scores after 1 min of study"] },
      { level: 10, features: ['Improved Combat Superiority — dice become d10; learn 2 more maneuvers'] },
      { level: 15, features: ['Relentless — regain 1 superiority die if you have none on initiative roll'] },
    ],
    eldritch_knight: [
      { level: 3, features: ['Spellcasting — abjuration & evocation cantrips and spells (INT)', 'Weapon Bond — summon bonded weapon telekinetically as bonus action'] },
      { level: 7, features: ['War Magic — bonus weapon attack after casting a cantrip'] },
      { level: 10, features: ['Eldritch Strike — hit with a weapon to impose disadvantage on saves vs your next spell'] },
      { level: 15, features: ['Arcane Charge — Action Surge can teleport up to 30ft before or after the extra action'] },
    ],
  },
  Rogue: {
    thief: [
      { level: 3, features: ['Fast Hands — bonus action to use Sleight of Hand, thieves\' tools, or Use an Object', "Second-Story Work — climb at full speed; add DEX mod to running jump distance"] },
      { level: 9, features: ['Supreme Sneak — advantage on Stealth when moving at half speed or less'] },
      { level: 13, features: ['Use Magic Device — ignore class, race, and level requirements on magic items'] },
      { level: 17, features: ["Thief's Reflexes — two turns in the first round of combat (second at initiative − 10)"] },
    ],
    assassin: [
      { level: 3, features: ["Assassinate — advantage on attacks vs creatures that haven't taken a turn; auto-crit against surprised targets", 'Bonus Proficiencies — disguise kit, poisoner\'s kit'] },
      { level: 9, features: ['Infiltration Expertise — create convincing false identities over 7 days'] },
      { level: 13, features: ['Impostor — perfectly mimic a person after 3 hours of close study'] },
      { level: 17, features: ['Death Strike — double damage on your first hit vs a surprised creature (CON save negates)'] },
    ],
    arcane_trickster: [
      { level: 3, features: ['Spellcasting — illusion & enchantment cantrips and spells (INT)', 'Mage Hand Legerdemain — invisible mage hand can pick locks, disarm traps, and pickpocket'] },
      { level: 9, features: ['Magical Ambush — impose disadvantage on saves vs your spells if you\'re hidden when you cast'] },
      { level: 13, features: ['Versatile Trickster — use mage hand to grant yourself advantage on attacks vs nearby creature'] },
      { level: 17, features: ["Spell Thief — steal a spell from a caster after their spell fails on a save against you"] },
    ],
  },
  Barbarian: {
    berserker: [
      { level: 3, features: ['Frenzy — bonus weapon attack on each turn while raging (gain 1 exhaustion when rage ends)'] },
      { level: 6, features: ['Mindless Rage — immune to charm and fright while raging; ongoing effects are suppressed'] },
      { level: 10, features: ['Intimidating Presence — frighten a creature within 30ft as an action (WIS save)'] },
      { level: 14, features: ['Retaliation — reaction attack against a creature that deals damage to you in melee'] },
    ],
    totem_warrior: [
      { level: 3, features: ['Spirit Seeker — Beast Sense and Speak with Animals as rituals', 'Totem Spirit — Bear (resist all non-psychic damage), Eagle (Dash as bonus action), or Wolf (allies have advantage on attacks vs enemies within 5ft of you)'] },
      { level: 6, features: ["Aspect of the Beast — Bear (carry capacity ×2), Eagle (see 1 mile clearly), Wolf (track at fast pace without penalty)"] },
      { level: 10, features: ['Spirit Walker — cast Commune with Nature as ritual once per long rest'] },
      { level: 14, features: ['Totemic Attunement — Bear (adjacent enemies have disadvantage on attacks vs others), Eagle (fly at walking speed while raging), Wolf (knock an enemy prone after hitting them)'] },
    ],
    zealot: [
      { level: 3, features: ['Divine Fury — deal 1d6 + ½ Barbarian level radiant or necrotic on your first hit each turn while raging', 'Warrior of the Gods — resurrection spells targeting you cost no material components'] },
      { level: 6, features: ['Fanatical Focus — reroll one failed saving throw while raging (1/rage)'] },
      { level: 10, features: ['Zealous Presence — use Rage as bonus action to grant 10 creatures advantage on attacks and saves for 1 min (1/long rest)'] },
      { level: 14, features: ['Rage Beyond Death — remain at 1 HP (not 0) while raging; die when rage ends'] },
    ],
  },
  Ranger: {
    hunter: [
      { level: 3, features: ["Hunter's Prey — choose Colossus Slayer (+1d8 on a wounded target), Giant Killer (reaction attack when a Large+ creature misses you), or Horde Breaker (extra attack vs an adjacent enemy)"] },
      { level: 7, features: ['Defensive Tactics — Escape the Horde (no opportunity attacks), Multiattack Defense (+4 AC after being hit), or Steel Will (advantage on saves vs fright)'] },
      { level: 11, features: ['Multiattack — Volley (bow attack every creature in a 10ft radius) or Whirlwind Attack (melee attack every creature within 5ft)'] },
      { level: 15, features: ["Superior Hunter's Defense — Evasion, Stand Against the Tide (redirect missed attack), or Uncanny Dodge"] },
    ],
    beastmaster: [
      { level: 3, features: ["Ranger's Companion — bond with a CR ¼ or lower beast that obeys your commands and fights for you"] },
      { level: 7, features: ['Exceptional Training — your companion can Dash, Disengage, or Help as a bonus action'] },
      { level: 11, features: ['Bestial Fury — your companion makes two attacks when you command it to attack'] },
      { level: 15, features: ['Share Spells — spells you cast targeting yourself also affect your companion if within 30ft'] },
    ],
    gloom_stalker: [
      { level: 3, features: ['Dread Ambusher — +10ft speed on first turn; extra attack; deal +1d8 damage on first hit', 'Umbral Sight — invisible to creatures using darkvision in darkness', 'Gloom Stalker Spells: Disguise Self, Rope Trick, Fear, Greater Invisibility, Seeming'] },
      { level: 7, features: ['Iron Mind — proficiency in WIS saves (or CHA/INT if already proficient)'] },
      { level: 11, features: ["Stalker's Flurry — once per turn, missing with an attack lets you make another attack immediately"] },
      { level: 15, features: ['Shadowy Dodge — reaction to impose disadvantage on an attack roll against you'] },
    ],
  },
  Paladin: {
    oath_of_devotion: [
      { level: 3, features: ['Sacred Weapon — Channel Divinity: add CHA mod to attack rolls for 1 min', 'Turn the Unholy — Channel Divinity: turn fiends and undead (WIS save)', 'Oath Spells: Protection from Evil and Good, Sanctuary, Lesser Restoration, Silence'] },
      { level: 7, features: ['Aura of Devotion — you and allies within 10ft are immune to the charmed condition'] },
      { level: 15, features: ['Purity of Spirit — always under the effects of Protection from Evil and Good'] },
      { level: 20, features: ['Holy Nimbus — 30ft aura that deals 10 radiant damage to enemies; advantage on saves vs fiend and undead spells'] },
    ],
    oath_of_vengeance: [
      { level: 3, features: ['Abjure Enemy — Channel Divinity: frighten or restrain a creature (WIS save)', 'Vow of Enmity — Channel Divinity: advantage on attacks against one creature for 1 min', 'Oath Spells: Bane, Hunter\'s Mark, Hold Person, Misty Step'] },
      { level: 7, features: ['Relentless Avenger — free movement equal to half speed after landing an opportunity attack'] },
      { level: 15, features: ['Soul of Vengeance — reaction attack when your vowed enemy makes an attack roll'] },
      { level: 20, features: ['Avenging Angel — fly 60ft, aura frightens enemies within 30ft (WIS save)'] },
    ],
    oath_of_the_ancients: [
      { level: 3, features: ["Nature's Wrath — Channel Divinity: restrain a creature in spectral vines (STR or DEX save)", 'Turn the Faithless — Channel Divinity: turn fey and fiends (WIS save)', 'Oath Spells: Ensnaring Strike, Speak with Animals, Moonbeam, Misty Step'] },
      { level: 7, features: ['Aura of Warding — you and allies within 10ft have resistance to damage from spells'] },
      { level: 15, features: ['Undying Sentinel — when you drop to 0 HP, you drop to 1 instead (1/long rest)'] },
      { level: 20, features: ['Elder Champion — regain 10 HP at start of each turn; cast oath spells as bonus action; plants and animals aid you'] },
    ],
  },
  Monk: {
    open_hand: [
      { level: 3, features: ["Open Hand Technique — on each Flurry of Blows hit: push 15ft (STR save), knock prone (DEX save), or remove the target's reactions until your next turn"] },
      { level: 6, features: ['Wholeness of Body — heal yourself for 3× your Monk level (1/long rest)'] },
      { level: 11, features: ['Tranquility — Sanctuary effect that lasts until the start of your next turn or until you attack'] },
      { level: 17, features: ['Quivering Palm — set vibrations in a body on a hit; use an action to drop the creature to 0 HP (CON save reduces to 10d10 necrotic)'] },
    ],
    shadow: [
      { level: 3, features: ['Shadow Arts — spend 2 ki to cast Darkness, Darkvision, Pass Without Trace, or Silence', 'Darkvision 60ft granted permanently'] },
      { level: 6, features: ['Shadow Step — bonus action teleport between dim light or darkness within 60ft; advantage on next melee attack'] },
      { level: 11, features: ['Cloak of Shadows — become invisible in dim light or darkness as an action (until you attack or step into bright light)'] },
      { level: 17, features: ['Opportunist — reaction attack when a creature adjacent to you is hit by an ally'] },
    ],
    four_elements: [
      { level: 3, features: ['Disciple of the Elements — spend ki to fuel elemental disciplines (Fist of Unbroken Air, Fangs of the Fire Snake, Gong of the Summit, Rush of the Gale Spirits, Sweeping Cinder Strike, Water Whip)'] },
      { level: 6, features: ['Additional Disciplines — Clench of the North Wind (paralyze with cold), Eternal Mountain Defense (stone skin)'] },
      { level: 11, features: ['Additional Disciplines — Flames of the Phoenix, Mist Stance (gaseous form), Ride the Wind (fly)'] },
      { level: 17, features: ['Additional Disciplines — Breath of Winter, River of Hungry Flame, Wave of Rolling Earth'] },
    ],
  },
  Cleric: {
    life: [
      { level: 1, features: ['Bonus Proficiency — heavy armor', 'Disciple of Life — healing spells restore an extra 2 + spell level HP', 'Domain Spells: Bless, Cure Wounds, Lesser Restoration, Spiritual Weapon'] },
      { level: 2, features: ['Preserve Life — Channel Divinity: distribute up to 5× Cleric level HP among creatures at or below half max HP'] },
      { level: 6, features: ['Blessed Healer — regain HP equal to 2 + spell level when you cast a healing spell on someone else'] },
      { level: 8, features: ['Divine Strike — once per turn, +1d8 radiant damage on a weapon attack'] },
    ],
    light: [
      { level: 1, features: ['Bonus Cantrip — Light cantrip', 'Warding Flare — impose disadvantage on an attack against you (WIS mod uses/long rest)', 'Domain Spells: Burning Hands, Faerie Fire, Flaming Sphere, Scorching Ray'] },
      { level: 2, features: ['Radiance of the Dawn — Channel Divinity: 30ft burst dispels magical darkness and deals 2d10 + Cleric level radiant (CON save halves)'] },
      { level: 6, features: ['Improved Flare — use Warding Flare to protect other creatures you can see, not just yourself'] },
      { level: 8, features: ['Potent Spellcasting — add WIS modifier to damage rolls of cleric cantrips'] },
    ],
    war: [
      { level: 1, features: ['Bonus Proficiencies — martial weapons and heavy armor', 'War Priest — bonus attack when you use the Attack action (WIS mod uses/long rest)', 'Domain Spells: Divine Favor, Shield of Faith, Magic Weapon, Spiritual Weapon'] },
      { level: 2, features: ['Guided Strike — Channel Divinity: +10 bonus to an attack roll', "War God's Blessing — reaction Channel Divinity: give an adjacent ally +10 to their attack roll"] },
      { level: 6, features: ["War God's Blessing — can now be used at range (not just adjacent)"] },
      { level: 8, features: ["Divine Strike — once per turn, +1d8 damage (your deity's damage type) on a weapon attack"] },
    ],
  },
  Druid: {
    land: [
      { level: 2, features: ['Bonus Cantrip — one extra druid cantrip of your choice', 'Natural Recovery — recover spell slots totaling up to ½ Druid level on a short rest (1/long rest)', 'Circle Spells — bonus spells based on terrain type (Arctic, Coast, Desert, Forest, Grassland, Mountain, Swamp, or Underdark)'] },
      { level: 6, features: ["Land's Stride — move through non-magical difficult terrain at no extra cost; plants can't impede you"] },
      { level: 10, features: ["Nature's Ward — immune to poison and disease; fey and elementals can't charm or frighten you"] },
      { level: 14, features: ["Nature's Sanctuary — beasts and plants must make WIS saves to attack you; most will find easier prey"] },
    ],
    moon: [
      { level: 2, features: ['Combat Wild Shape — transform as a bonus action; spend spell slots as bonus action to heal 1d8 per slot level while transformed', 'Circle Forms — Wild Shape into CR 1 beasts (CR = ⅓ Druid level at higher levels)'] },
      { level: 6, features: ['Primal Strike — beast form attacks count as magical for overcoming resistance'] },
      { level: 10, features: ['Elemental Wild Shape — spend 2 Wild Shape uses to transform into an air, earth, fire, or water elemental'] },
      { level: 14, features: ['Thousand Forms — cast Alter Self at will'] },
    ],
    spores: [
      { level: 2, features: ['Halo of Spores — reaction: deal 1d4 necrotic when a creature moves within 10ft (CON save)', 'Symbiotic Entity — expend Wild Shape to gain 4× Druid level THP and improve Halo of Spores damage'] },
      { level: 6, features: ["Fungal Infestation — reanimate Small/Medium humanoids that die within 10ft as zombies under your control (1 per creature)"] },
      { level: 10, features: ['Spreading Spores — bonus action to move Halo of Spores to a 10ft cube for 1 min (can\'t do both simultaneously)'] },
      { level: 14, features: ['Fungal Body — immune to blinded, deafened, frightened, and poisoned; critical hits against you become normal hits'] },
    ],
  },
  Wizard: {
    evocation: [
      { level: 2, features: ['Evocation Savant — copy evocation spells for half the gold and time', 'Sculpt Spells — protect up to 1 + spell level creatures inside your area-of-effect evocation spells (they automatically succeed on saves and take no damage)'] },
      { level: 6, features: ['Potent Cantrip — targets that succeed on saves against your cantrips still take half damage'] },
      { level: 10, features: ['Empowered Evocation — add INT modifier to the damage of any evocation spell you cast'] },
      { level: 14, features: ['Overchannel — maximize damage of a L1–5 evocation spell; second use causes 2d12 necrotic to yourself per spell level'] },
    ],
    abjuration: [
      { level: 2, features: ['Abjuration Savant — copy abjuration spells for half the gold and time', 'Arcane Ward — casting abjuration spells creates/refills a ward with HP = 2× Wizard level + INT mod; absorbs damage before you do'] },
      { level: 6, features: ['Projected Ward — redirect damage from a creature within 30ft to your Arcane Ward instead'] },
      { level: 10, features: ['Improved Abjuration — add proficiency bonus to ability checks made as part of casting abjuration spells'] },
      { level: 14, features: ['Spell Resistance — advantage on saving throws against spells; resistance to spell damage'] },
    ],
    illusion: [
      { level: 2, features: ['Illusion Savant — copy illusion spells for half the gold and time', 'Improved Minor Illusion — cast Minor Illusion creating both a sound and an image simultaneously'] },
      { level: 6, features: ['Malleable Illusions — use an action to change the nature of an ongoing illusion spell'] },
      { level: 10, features: ['Illusory Self — reaction: create an illusory duplicate that causes one attack to miss you (1/short rest)'] },
      { level: 14, features: ['Illusory Reality — one non-creature object in a spell illusion becomes real for 1 minute'] },
    ],
  },
  Bard: {
    lore: [
      { level: 3, features: ['Bonus Proficiencies — 3 additional skills of your choice', "Cutting Words — reaction: subtract a Bardic Inspiration die from a creature's attack roll, ability check, or damage roll"] },
      { level: 6, features: ['Additional Magical Secrets — learn 2 spells from any class spell list'] },
      { level: 14, features: ['Peerless Skill — add a Bardic Inspiration die to your own ability checks'] },
    ],
    valor: [
      { level: 3, features: ['Bonus Proficiencies — medium armor, shields, and martial weapons', 'Combat Inspiration — creatures can use Bardic Inspiration die to add to a damage roll or their AC against one attack'] },
      { level: 6, features: ['Extra Attack — attack twice when you take the Attack action'] },
      { level: 14, features: ['Battle Magic — bonus action weapon attack after casting a bard spell using your action'] },
    ],
    glamour: [
      { level: 3, features: ['Mantle of Inspiration — spend Bardic Inspiration: up to 5 creatures gain THP and free movement without provoking opportunity attacks', 'Enthralling Performance — charm creatures for 1 hour after a 1-min performance (WIS save)'] },
      { level: 6, features: ["Mantle of Majesty — bonus action to cast Command each turn for 1 min while maintaining a majestic presence (CHA vs WIS)"] },
      { level: 14, features: ['Unbreakable Majesty — assume majesty for 1 min; attackers must succeed on CHA save or be forced to target a different creature'] },
    ],
  },
  Sorcerer: {
    draconic: [
      { level: 1, features: ['Dragon Ancestor — choose a draconic ancestry type (gives a damage affinity and language)', 'Draconic Resilience — AC 13 + DEX mod without armor; gain +1 max HP per Sorcerer level'] },
      { level: 6, features: ['Elemental Affinity — add CHA mod to one damage roll of your dragon type; spend 1 sorcery point for 1-hour resistance to that damage'] },
      { level: 14, features: ['Dragon Wings — bonus action to sprout dragon wings; fly speed equals walking speed'] },
      { level: 18, features: ['Draconic Presence — spend 5 sorcery points to awe or frighten creatures within 60ft for 1 min (WIS save)'] },
    ],
    wild_magic: [
      { level: 1, features: ['Wild Magic Surge — DM may have you roll on the Wild Magic table after casting a L1+ spell', 'Tides of Chaos — advantage on one attack, check, or save (1/long rest); triggers a Wild Magic Surge when used'] },
      { level: 6, features: ["Bend Luck — spend 2 sorcery points to add or subtract 1d4 from any creature's d20 roll"] },
      { level: 14, features: ['Controlled Chaos — roll twice on the Wild Magic Surge table and choose which effect occurs'] },
      { level: 18, features: ['Spell Bombardment — when you roll the maximum value on a spell damage die, roll that die again and add the result'] },
    ],
    storm: [
      { level: 1, features: ['Wind Speaker — speak, read, and write Primordial (covers Aquan, Auran, Ignan, Terran)', 'Tempestuous Magic — bonus action after casting a L1+ spell: fly 10ft without provoking opportunity attacks'] },
      { level: 6, features: ['Heart of the Storm — resistance to lightning and thunder; deal CHA mod lightning or thunder damage to nearby creatures when you cast a L1+ spell', 'Storm Guide — suppress rain or wind in your vicinity at will'] },
      { level: 14, features: ["Storm's Fury — reaction when hit in melee: deal 2d6 lightning and push attacker 20ft (STR save negates push)"] },
      { level: 18, features: ['Wind Soul — immunity to lightning and thunder; fly 60ft; spend 1 min to give up to 3 allies a 30ft fly speed'] },
    ],
  },
  Warlock: {
    fiend: [
      { level: 1, features: ["Dark One's Blessing — on killing a creature, gain THP equal to CHA mod + Warlock level", 'Expanded Spell List: Burning Hands, Command, Blindness/Deafness, Scorching Ray, Fireball, Stinking Cloud'] },
      { level: 6, features: ["Dark One's Own Luck — add d10 to one ability check or saving throw (1/short rest)"] },
      { level: 10, features: ['Fiendish Resilience — choose one damage type; gain resistance to it until next short rest'] },
      { level: 14, features: ['Hurl Through Hell — on a hit, banish target to a hellish nightmare for 1 round, dealing 10d10 psychic on return (WIS save negates damage)'] },
    ],
    archfey: [
      { level: 1, features: ['Fey Presence — bonus action: charmed or frightened creatures in a 10ft cube (WIS save, 1/short rest)', 'Expanded Spell List: Faerie Fire, Sleep, Calm Emotions, Phantasmal Force, Blink, Plant Growth'] },
      { level: 6, features: ['Misty Escape — reaction on taking damage: go invisible and teleport up to 60ft (ends invisibility if you attack or cast)'] },
      { level: 10, features: ['Beguiling Defenses — immune to charm; reaction to turn a charm attempt back on the caster for 1 min'] },
      { level: 14, features: ["Dark Delirium — send one creature into a dream world for 1 min (WIS save); charmed or frightened, can't see beyond 30ft"] },
    ],
    great_old_one: [
      { level: 1, features: ['Awakened Mind — telepathic communication with any creature within 30ft (no shared language needed)', "Expanded Spell List: Dissonant Whispers, Tasha's Hideous Laughter, Detect Thoughts, Phantasmal Force, Clairvoyance, Sending"] },
      { level: 6, features: ['Entropic Ward — reaction to impose disadvantage on one attack roll; if it misses, advantage on your next attack (1/short rest)'] },
      { level: 10, features: ['Thought Shield — immunity to telepathy; resistance to psychic damage; attacker takes equal psychic damage'] },
      { level: 14, features: ['Create Thrall — touch an incapacitated humanoid to charm it indefinitely; communicate telepathically with it at any distance'] },
    ],
  },
};
